name: Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject PostHog API key
        env:
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
        run: |
          if [ -z "$POSTHOG_API_KEY" ]; then
            echo "::error::POSTHOG_API_KEY secret is not configured. Add it in the repository settings before deploying."
            exit 1
          fi

          sed -i "s#<meta name=\"posthog-key\" content=\"\">#<meta name=\"posthog-key\" content=\"${POSTHOG_API_KEY}\">#" docs/index.html

      - name: Upload static site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
